#Quintupla:
#entradas 
sigma = [
    "<Manutenção>", "(Identidade Válida)", "(Identidade Inválida)", "<Voltar>", "<Reposição>", "<Repor 1>", "<Repor Tudo>", "<Comprar>", "<Cartão>", "<Dinheiro>", 
    "<1>", "<2>", "<3>", "<4>", "<5>", "<6>", "<7>", "<8>", "<9>", "<10>", 
    "<11>", "<12>", "<13>", "<14>", "<15>", "<16>", "<17>", "<18>", "<19>", "<20>", 
    "(Reposto 1 1)", "(Reposto 1 2)", "(Reposto 1 3)", "(Reposto 1 4)", "(Reposto 1 5)", "(Reposto 1 6)", "(Reposto 1 7)", "(Reposto 1 8)", "(Reposto 1 9)", "(Reposto 1 10)", 
    "(Reposto 1 11)", "(Reposto 1 12)", "(Reposto 1 13)", "(Reposto 1 14)", "(Reposto 1 15)", "(Reposto 1 16)", "(Reposto 1 17)", "(Reposto 1 18)", "(Reposto 1 19)", "(Reposto 1 20)", 
    "(Reposto Tudo 1)", "(Reposto Tudo 2)", "(Reposto Tudo 3)", "(Reposto Tudo 4)", "(Reposto Tudo 5)", "(Reposto Tudo 6)", "(Reposto Tudo 7)", "(Reposto Tudo 8)", "(Reposto Tudo 9)", "(Reposto Tudo 10)", 
    "(Reposto Tudo 11)", "(Reposto Tudo 12)", "(Reposto Tudo 13)", "(Reposto Tudo 14)", "(Reposto Tudo 15)", "(Reposto Tudo 16)", "(Reposto Tudo 17)", "(Reposto Tudo 18)", "(Reposto Tudo 19)", "(Reposto Tudo 20)", 
    "Sem Estoque 1)", "(Sem Estoque 2)", "(Sem Estoque 3)", "(Sem Estoque 4)", "(Sem Estoque 5)", "(Sem Estoque 6)", "(Sem Estoque 7)", "(Sem Estoque 8)", "(Sem Estoque 9)", "(Sem Estoque 10)", 
    "(Sem Estoque 11)", "(Sem Estoque 12)", "(Sem Estoque 13)", "(Sem Estoque 14)", "(Sem Estoque 15)", "(Sem Estoque 16)", "(Sem Estoque 17)", "(Sem Estoque 18)", "(Sem Estoque 19)", "(Sem Estoque 20)", 
    "(Com Estoque 1)", "(Com Estoque 2)", "(Com Estoque 3)", "(Com Estoque 4)", "(Com Estoque 5)", "(Com Estoque 6)", "(Com Estoque 7)", "(Com Estoque 8)", "(Com Estoque 9)", "(Com Estoque 10)", 
    "(Com Estoque 11)", "(Com Estoque 12)", "(Com Estoque 13)", "(Com Estoque 14)", "(Com Estoque 15)", "(Com Estoque 16)", "(Com Estoque 17)", "(Com Estoque 18)", "(Com Estoque 19)", "(Com Estoque 20)", 
    "(Falha 1)", "(Falha 2)", "(Falha 3)", "(Falha 4)", "(Falha 5)", "(Falha 6)", "(Falha 7)", "(Falha 8)", "(Falha 9)", "(Falha 10)", 
    "(Falha 11)", "(Falha 12)", "(Falha 13)", "(Falha 14)", "(Falha 15)", "(Falha 16)", "(Falha 17)", "(Falha 18)", "(Falha 19)", "(Falha 20)", 
    "(Aceito 1)", "(Aceito 2)", "(Aceito 3)", "(Aceito 4)", "(Aceito 5)", "(Aceito 6)", "(Aceito 7)", "(Aceito 8)", "(Aceito 9)", "(Aceito 10)", 
    "Aceito 11)", "(Aceito 12)", "(Aceito 13)", "(Aceito 14)", "(Aceito 15)", "(Aceito 16)", "(Aceito 17)", "(Aceito 18)", "(Aceito 19)", "(Aceito 20)"
    ]
#estados
Q = [
    "Base", "Manutenção Verificação", "Manutenção", "Reposição Verificação", "Reposição", "Venda", 
    "Reposição 1", "Reposição 2", "Reposição 3", "Reposição 4", "Reposição 5", "Reposição 6", "Reposição 7", "Reposição 8", "Reposição 9", "Reposição 10", 
    "Reposição 11", "Reposição 12", "Reposição 13", "Reposição 14", "Reposição 15", "Reposição 16", "Reposição 17", "Reposição 18", "Reposição 19", "Reposição 20", 
    "Reposto 1 1", "Reposto 1 2", "Reposto 1 3", "Reposto 1 4", "Reposto 1 5", "Reposto 1 6", "Reposto 1 7", "Reposto 1 8", "Reposto 1 9", "Reposto 1 10", 
    "Reposto 1 11", "Reposto 1 12", "Reposto 1 13", "Reposto 1 14", "Reposto 1 15", "Reposto 1 16", "Reposto 1 17", "Reposto 1 18", "Reposto 1 19", "Reposto 1 20", 
    "Reposto Tudo 1", "Reposto Tudo 2", "Reposto Tudo 3", "Reposto Tudo 4", "Reposto Tudo 5", "Reposto Tudo 6", "Reposto Tudo 7", "Reposto Tudo 8", "Reposto Tudo 9", "Reposto Tudo 10", 
    "Reposto Tudo 11", "Reposto Tudo 12", "Reposto Tudo 13", "Reposto Tudo 14", "Reposto Tudo 15", "Reposto Tudo 16", "Reposto Tudo 17", "Reposto Tudo 18", "Reposto Tudo 19", "Reposto Tudo 20", 
    "enda 1", "Venda 2", "Venda 3", "Venda 4", "Venda 5", "Venda 6", "Venda 7", "Venda 8", "Venda 9", "Venda 10", "Venda 11", "Venda 12", "Venda 13", "Venda 14", "Venda 15", "Venda 16", "Venda 17", "Venda 18", "Venda 19", "Venda 20", 
    "Método Pagamento 1", "Método Pagamento 2", "Método Pagamento 3", "Método Pagamento 4", "Método Pagamento 5", "Método Pagamento 6", "Método Pagamento 7", "Método Pagamento 8", "Método Pagamento 9", "Método Pagamento 10", 
    "Método Pagamento 11", "Método Pagamento 12", "Método Pagamento 13", "Método Pagamento 14", "Método Pagamento 15", "Método Pagamento 16", "Método Pagamento 17", "Método Pagamento 18", "Método Pagamento 19", "Método Pagamento 20", 
    "Verificação Pagamento 1", "Verificação Pagamento 2", "Verificação Pagamento 3", "Verificação Pagamento 4", "Verificação Pagamento 5", "Verificação Pagamento 6", "Verificação Pagamento 7", "Verificação Pagamento 8", "Verificação Pagamento 9", "Verificação Pagamento 10", 
    "Verificação Pagamento 11", "Verificação Pagamento 12", "Verificação Pagamento 13", "Verificação Pagamento 14", "Verificação Pagamento 15", "Verificação Pagamento 16", "Verificação Pagamento 17", "Verificação Pagamento 18", "Verificação Pagamento 19", "Verificação Pagamento 20"
    ]
#transiçoes
producao = [
    ("Base", "<Manutenção>", "Manutenção Verificação", "[Verificar Identificação]"),
    ("Manutenção Verificação", "(Identidade Inválida)", "Base", "Id inválida, tente novamente"),
    ("Manutenção Verificação", "(Identidade Válida)", "Manutenção", "Maquina desabilitada para manutenção"),
    ("Manutenção", "<Voltar>", "Base", "Voltando a operação normal"),
    ("Base", "<Reposição>", "Reposição Verificação", "ε"),
    ("Reposição Verificação", "(Identidade Invalida)", "Base", "Id inválida, tente novamente"),
    ("Reposição Verificação", "(Identidade Válida)", "Reposição", "Digite o ID do produto"),
    ("Reposição", "<Voltar>", "Base", "Voltando a operação normal"),
    ("Reposição", "<1>", "Reposição 1", "Repor 1, Tudo ou Voltar?"),
    ("Reposição", "<2>", "Reposição 2", "Repor 1, Tudo ou Voltar?"),
    ("Reposição", "<3>", "Reposição 3", "Repor 1, Tudo ou Voltar?"),
    ("Reposição", "<4>", "Reposição 4", "Repor 1, Tudo ou Voltar?"),
    ("Reposição", "<5>", "Reposição 5", "Repor 1, Tudo ou Voltar?"),
    ("Reposição", "<6>", "Reposição 6", "Repor 1, Tudo ou Voltar?"),
    ("Reposição", "<7>", "Reposição 7", "Repor 1, Tudo ou Voltar?"),
    ("Reposição", "<8>", "Reposição 8", "Repor 1, Tudo ou Voltar?"),
    ("Reposição", "<9>", "Reposição 9", "Repor 1, Tudo ou Voltar?"),
    ("Reposição", "<10>", "Reposição 10", "Repor 1, Tudo ou Voltar?"),
    ("Reposição", "<11>", "Reposição 11", "Repor 1, Tudo ou Voltar?"),
    ("Reposição", "<12>", "Reposição 12", "Repor 1, Tudo ou Voltar?"),
    ("Reposição", "<13>", "Reposição 13", "Repor 1, Tudo ou Voltar?"),
    ("Reposição", "<14>", "Reposição 14", "Repor 1, Tudo ou Voltar?"),
    ("Reposição", "<15>", "Reposição 15", "Repor 1, Tudo ou Voltar?"),
    ("Reposição", "<16>", "Reposição 16", "Repor 1, Tudo ou Voltar?"),
    ("Reposição", "<17>", "Reposição 17", "Repor 1, Tudo ou Voltar?"),
    ("Reposição", "<18>", "Reposição 18", "Repor 1, Tudo ou Voltar?"),
    ("Reposição", "<19>", "Reposição 19", "Repor 1, Tudo ou Voltar?"),
    ("Reposição", "<20>", "Reposição 20", "Repor 1, Tudo ou Voltar?"),
    ("Reposição 1", "<Repor 1>", "Reposto 1 1", "Reposto 1 Item, [Repor 1 1]"),
    ("Reposição 2", "<Repor 1>", "Reposto 1 2", "Reposto 1 Item, [Repor 1 2]"),
    ("Reposição 3", "<Repor 1>", "Reposto 1 3", "Reposto 1 Item, [Repor 1 3]"),
    ("Reposição 4", "<Repor 1>", "Reposto 1 4", "Reposto 1 Item, [Repor 1 4]"),
    ("Reposição 5", "<Repor 1>", "Reposto 1 5", "Reposto 1 Item, [Repor 1 5]"),
    ("Reposição 6", "<Repor 1>", "Reposto 1 6", "Reposto 1 Item, [Repor 1 6]"),
    ("Reposição 7", "<Repor 1>", "Reposto 1 7", "Reposto 1 Item, [Repor 1 7]"),
    ("Reposição 8", "<Repor 1>", "Reposto 1 8", "Reposto 1 Item, [Repor 1 8]"),
    ("Reposição 9", "<Repor 1>", "Reposto 1 9", "Reposto 1 Item, [Repor 1 9]"),
    ("Reposição 10", "<Repor 1>", "Reposto 1 10", "Reposto 1 Item, [Repor 1 10]"),
    ("Reposição 11", "<Repor 1>", "Reposto 1 11", "Reposto 1 Item, [Repor 1 11]"),
    ("Reposição 12", "<Repor 1>", "Reposto 1 12", "Reposto 1 Item, [Repor 1 12]"),
    ("Reposição 13", "<Repor 1>", "Reposto 1 13", "Reposto 1 Item, [Repor 1 13]"),
    ("Reposição 14", "<Repor 1>", "Reposto 1 14", "Reposto 1 Item, [Repor 1 14]"),
    ("Reposição 15", "<Repor 1>", "Reposto 1 15", "Reposto 1 Item, [Repor 1 15]"),
    ("Reposição 16", "<Repor 1>", "Reposto 1 16", "Reposto 1 Item, [Repor 1 16]"),
    ("Reposição 17", "<Repor 1>", "Reposto 1 17", "Reposto 1 Item, [Repor 1 17]"),
    ("Reposição 18", "<Repor 1>", "Reposto 1 18", "Reposto 1 Item, [Repor 1 18]"),
    ("Reposição 19", "<Repor 1>", "Reposto 1 19", "Reposto 1 Item, [Repor 1 19]"),
    ("Reposição 20", "<Repor 1>", "Reposto 1 20", "Reposto 1 Item, [Repor 1 19]"),
    ("Reposição 1", "<Repor Tudo>", "Reposto Tudo 1", "Reposto todos Itens, [Repor Tudo 1]"),
    ("Reposição 2", "<Repor Tudo>", "Reposto Tudo 2", "Reposto todos Itens, [Repor Tudo 2]"),
    ("Reposição 3", "<Repor Tudo>", "Reposto Tudo 3", "Reposto todos Itens, [Repor Tudo 3]"),
    ("Reposição 4", "<Repor Tudo>", "Reposto Tudo 4", "Reposto todos Itens, [Repor Tudo 4]"),
    ("Reposição 5", "<Repor Tudo>", "Reposto Tudo 5", "Reposto todos Itens, [Repor Tudo 5]"),
    ("Reposição 6", "<Repor Tudo>", "Reposto Tudo 6", "Reposto todos Itens, [Repor Tudo 6]"),
    ("Reposição 7", "<Repor Tudo>", "Reposto Tudo 7", "Reposto todos Itens, [Repor Tudo 7]"),
    ("Reposição 8", "<Repor Tudo>", "Reposto Tudo 8", "Reposto todos Itens, [Repor Tudo 8]"),
    ("Reposição 9", "<Repor Tudo>", "Reposto Tudo 9", "Reposto todos Itens, [Repor Tudo 9]"),
    ("Reposição 10", "<Repor Tudo>", "Reposto Tudo 10", "Reposto todos Itens, [Repor Tudo 10]"),
    ("Reposição 11", "<Repor Tudo>", "Reposto Tudo 11", "Reposto todos Itens, [Repor Tudo 11]"),
    ("Reposição 12", "<Repor Tudo>", "Reposto Tudo 12", "Reposto todos Itens, [Repor Tudo 12]"),
    ("Reposição 13", "<Repor Tudo>", "Reposto Tudo 13", "Reposto todos Itens, [Repor Tudo 13]"),
    ("Reposição 14", "<Repor Tudo>", "Reposto Tudo 14", "Reposto todos Itens, [Repor Tudo 14]"),
    ("Reposição 15", "<Repor Tudo>", "Reposto Tudo 15", "Reposto todos Itens, [Repor Tudo 15]"),
    ("Reposição 16", "<Repor Tudo>", "Reposto Tudo 16", "Reposto todos Itens, [Repor Tudo 16]"),
    ("Reposição 17", "<Repor Tudo>", "Reposto Tudo 17", "Reposto todos Itens, [Repor Tudo 17]"),
    ("Reposição 18", "<Repor Tudo>", "Reposto Tudo 18", "Reposto todos Itens, [Repor Tudo 18]"),
    ("Reposição 19", "<Repor Tudo>", "Reposto Tudo 19", "Reposto todos Itens, [Repor Tudo 19]"),
    ("Reposição 20", "<Repor Tudo>", "Reposto Tudo 20", "Reposto todos Itens, [Repor Tudo 19]"),
    ("Reposto 1 1", "(Reposto 1 1)", "Base", "ε"),
    ("Reposto 1 2", "(Reposto 1 2)", "Base", "ε"),
    ("Reposto 1 3", "(Reposto 1 3)", "Base", "ε"),
    ("Reposto 1 4", "(Reposto 1 4)", "Base", "ε"),
    ("Reposto 1 5", "(Reposto 1 5)", "Base", "ε"),
    ("Reposto 1 6", "(Reposto 1 6)", "Base", "ε"),
    ("Reposto 1 7", "(Reposto 1 7)", "Base", "ε"),
    ("Reposto 1 8", "(Reposto 1 8)", "Base", "ε"),
    ("Reposto 1 9", "(Reposto 1 9)", "Base", "ε"),
    ("Reposto 1 10", "(Reposto 1 10)", "Base", "ε"),
    ("Reposto 1 11", "(Reposto 1 11)", "Base", "ε"),
    ("Reposto 1 12", "(Reposto 1 12)", "Base", "ε"),
    ("Reposto 1 13", "(Reposto 1 13)", "Base", "ε"),
    ("Reposto 1 14", "(Reposto 1 14)", "Base", "ε"),
    ("Reposto 1 15", "(Reposto 1 15)", "Base", "ε"),
    ("Reposto 1 16", "(Reposto 1 16)", "Base", "ε"),
    ("Reposto 1 17", "(Reposto 1 17)", "Base", "ε"),
    ("Reposto 1 18", "(Reposto 1 18)", "Base", "ε"),
    ("Reposto 1 19", "(Reposto 1 19)", "Base", "ε"),
    ("Reposto 1 20", "(Reposto 1 20)", "Base", "ε"),
    ("Reposto Tudo 1", "(Reposto Tudo 1)", "Base", "ε"),
    ("Reposto Tudo 2", "(Reposto Tudo 2)", "Base", "ε"),
    ("Reposto Tudo 3", "(Reposto Tudo 3)", "Base", "ε"),
    ("Reposto Tudo 4", "(Reposto Tudo 4)", "Base", "ε"),
    ("Reposto Tudo 5", "(Reposto Tudo 5)", "Base", "ε"),
    ("Reposto Tudo 6", "(Reposto Tudo 6)", "Base", "ε"),
    ("Reposto Tudo 7", "(Reposto Tudo 7)", "Base", "ε"),
    ("Reposto Tudo 8", "(Reposto Tudo 8)", "Base", "ε"),
    ("Reposto Tudo 9", "(Reposto Tudo 9)", "Base", "ε"),
    ("Reposto Tudo 10", "(Reposto Tudo 10)", "Base", "ε"),
    ("Reposto Tudo 11", "(Reposto Tudo 11)", "Base", "ε"),
    ("Reposto Tudo 12", "(Reposto Tudo 12)", "Base", "ε"),
    ("Reposto Tudo 13", "(Reposto Tudo 13)", "Base", "ε"),
    ("Reposto Tudo 14", "(Reposto Tudo 14)", "Base", "ε"),
    ("Reposto Tudo 15", "(Reposto Tudo 15)", "Base", "ε"),
    ("Reposto Tudo 16", "(Reposto Tudo 16)", "Base", "ε"),
    ("Reposto Tudo 17", "(Reposto Tudo 17)", "Base", "ε"),
    ("Reposto Tudo 18", "(Reposto Tudo 18)", "Base", "ε"),
    ("Reposto Tudo 19", "(Reposto Tudo 19)", "Base", "ε"),
    ("Reposto Tudo 20", "(Reposto Tudo 20)", "Base", "ε"),
    ("Base", "<Comprar>", "Venda", "Qual ID do produto?"),
    ("Venda", "<Voltar>", "Base", "Voltando Menu Inicial"),
    ("Venda", "<1>", "Venda 1", "Verificando estoque, [Verificar estoque 1]"),
    ("Venda", "<2>", "Venda 2", "Verificando estoque, [Verificar estoque 2]"),
    ("Venda", "<3>", "Venda 3", "Verificando estoque, [Verificar estoque 3]"),
    ("Venda", "<4>", "Venda 4", "Verificando estoque, [Verificar estoque 4]"),
    ("Venda", "<5>", "Venda 5", "Verificando estoque, [Verificar estoque 5]"),
    ("Venda", "<6>", "Venda 6", "Verificando estoque, [Verificar estoque 6]"),
    ("Venda", "<7>", "Venda 7", "Verificando estoque, [Verificar estoque 7]"),
    ("Venda", "<8>", "Venda 8", "Verificando estoque, [Verificar estoque 8]"),
    ("Venda", "<9>", "Venda 9", "Verificando estoque, [Verificar estoque 9]"),
    ("Venda", "<10>", "Venda 10", "Verificando estoque, [Verificar estoque 10]"),
    ("Venda", "<11>", "Venda 11", "Verificando estoque, [Verificar estoque 11]"),
    ("Venda", "<12>", "Venda 12", "Verificando estoque, [Verificar estoque 12]"),
    ("Venda", "<13>", "Venda 13", "Verificando estoque, [Verificar estoque 13]"),
    ("Venda", "<14>", "Venda 14", "Verificando estoque, [Verificar estoque 14]"),
    ("Venda", "<15>", "Venda 15", "Verificando estoque, [Verificar estoque 15]"),
    ("Venda", "<16>", "Venda 16", "Verificando estoque, [Verificar estoque 16]"),
    ("Venda", "<17>", "Venda 17", "Verificando estoque, [Verificar estoque 17]"),
    ("Venda", "<18>", "Venda 18", "Verificando estoque, [Verificar estoque 18]"),
    ("Venda", "<19>", "Venda 19", "Verificando estoque, [Verificar estoque 19]"),
    ("Venda", "<20>", "Venda 20", "Verificando estoque, [Verificar estoque 20]"),
    ("Venda 1", "(Sem Estoque 1)", "Venda", "Estoque vazio, escolha outro item"),
    ("Venda 2", "(Sem Estoque 2)", "Venda", "Estoque vazio, escolha outro item"),
    ("Venda 3", "(Sem Estoque 3)", "Venda", "Estoque vazio, escolha outro item"),
    ("Venda 4", "(Sem Estoque 4)", "Venda", "Estoque vazio, escolha outro item"),
    ("Venda 5", "(Sem Estoque 5)", "Venda", "Estoque vazio, escolha outro item"),
    ("Venda 6", "(Sem Estoque 6)", "Venda", "Estoque vazio, escolha outro item"),
    ("Venda 7", "(Sem Estoque 7)", "Venda", "Estoque vazio, escolha outro item"),
    ("Venda 8", "(Sem Estoque 8)", "Venda", "Estoque vazio, escolha outro item"),
    ("Venda 9", "(Sem Estoque 9)", "Venda", "Estoque vazio, escolha outro item"),
    ("Venda 10", "(Sem Estoque 10)", "Venda", "Estoque vazio, escolha outro item"),
    ("Venda 11", "(Sem Estoque 11)", "Venda", "Estoque vazio, escolha outro item"),
    ("Venda 12", "(Sem Estoque 12)", "Venda", "Estoque vazio, escolha outro item"),
    ("Venda 13", "(Sem Estoque 13)", "Venda", "Estoque vazio, escolha outro item"),
    ("Venda 14", "(Sem Estoque 14)", "Venda", "Estoque vazio, escolha outro item"),
    ("Venda 15", "(Sem Estoque 15)", "Venda", "Estoque vazio, escolha outro item"),
    ("Venda 16", "(Sem Estoque 16)", "Venda", "Estoque vazio, escolha outro item"),
    ("Venda 17", "(Sem Estoque 17)", "Venda", "Estoque vazio, escolha outro item"),
    ("Venda 18", "(Sem Estoque 18)", "Venda", "Estoque vazio, escolha outro item"),
    ("Venda 19", "(Sem Estoque 19)", "Venda", "Estoque vazio, escolha outro item"),
    ("Venda 20", "(Sem Estoque 20)", "Venda", "Estoque vazio, escolha outro item"),
    ("Venda 1", "(Com Estoque 1)", "Método Pagamento 1", "Qual metodo de pagamento?"),
    ("Venda 2", "(Com Estoque 2)", "Método Pagamento 2", "Qual metodo de pagamento?"),
    ("Venda 3", "(Com Estoque 3)", "Método Pagamento 3", "Qual metodo de pagamento?"),
    ("Venda 4", "(Com Estoque 4)", "Método Pagamento 4", "Qual metodo de pagamento?"),
    ("Venda 5", "(Com Estoque 5)", "Método Pagamento 5", "Qual metodo de pagamento?"),
    ("Venda 6", "(Com Estoque 6)", "Método Pagamento 6", "Qual metodo de pagamento?"),
    ("Venda 7", "(Com Estoque 7)", "Método Pagamento 7", "Qual metodo de pagamento?"),
    ("Venda 8", "(Com Estoque 8)", "Método Pagamento 8", "Qual metodo de pagamento?"),
    ("Venda 9", "(Com Estoque 9)", "Método Pagamento 9", "Qual metodo de pagamento?"),
    ("Venda 10", "(Com Estoque 10)", "Método Pagamento 10", "Qual metodo de pagamento?"),
    ("Venda 11", "(Com Estoque 11)", "Método Pagamento 11", "Qual metodo de pagamento?"),
    ("Venda 12", "(Com Estoque 12)", "Método Pagamento 12", "Qual metodo de pagamento?"),
    ("Venda 13", "(Com Estoque 13)", "Método Pagamento 13", "Qual metodo de pagamento?"),
    ("Venda 14", "(Com Estoque 14)", "Método Pagamento 14", "Qual metodo de pagamento?"),
    ("Venda 15", "(Com Estoque 15)", "Método Pagamento 15", "Qual metodo de pagamento?"),
    ("Venda 16", "(Com Estoque 16)", "Método Pagamento 16", "Qual metodo de pagamento?"),
    ("Venda 17", "(Com Estoque 17)", "Método Pagamento 17", "Qual metodo de pagamento?"),
    ("Venda 18", "(Com Estoque 18)", "Método Pagamento 18", "Qual metodo de pagamento?"),
    ("Venda 19", "(Com Estoque 19)", "Método Pagamento 19", "Qual metodo de pagamento?"),
    ("Venda 20", "(Com Estoque 20)", "Método Pagamento 20", "Qual metodo de pagamento?"),
    ("Método Pagamento 1", "<Cartão>", "Verificação Pagamento 1", "[Verificar pagamento 1]"),
    ("Método Pagamento 2", "<Cartão>", "Verificação Pagamento 2", "[Verificar pagamento 2]"),
    ("Método Pagamento 3", "<Cartão>", "Verificação Pagamento 3", "[Verificar pagamento 3]"),
    ("Método Pagamento 4", "<Cartão>", "Verificação Pagamento 4", "[Verificar pagamento 4]"),
    ("Método Pagamento 5", "<Cartão>", "Verificação Pagamento 5", "[Verificar pagamento 5]"),
    ("Método Pagamento 6", "<Cartão>", "Verificação Pagamento 6", "[Verificar pagamento 6]"),
    ("Método Pagamento 7", "<Cartão>", "Verificação Pagamento 7", "[Verificar pagamento 7]"),
    ("Método Pagamento 8", "<Cartão>", "Verificação Pagamento 8", "[Verificar pagamento 8]"),
    ("Método Pagamento 9", "<Cartão>", "Verificação Pagamento 9", "[Verificar pagamento 9]"),
    ("Método Pagamento 10", "<Cartão>", "Verificação Pagamento 10", "[Verificar pagamento 10]"),
    ("Método Pagamento 11", "<Cartão>", "Verificação Pagamento 11", "[Verificar pagamento 11]"),
    ("Método Pagamento 12", "<Cartão>", "Verificação Pagamento 12", "[Verificar pagamento 12]"),
    ("Método Pagamento 13", "<Cartão>", "Verificação Pagamento 13", "[Verificar pagamento 13]"),
    ("Método Pagamento 14", "<Cartão>", "Verificação Pagamento 14", "[Verificar pagamento 14]"),
    ("Método Pagamento 15", "<Cartão>", "Verificação Pagamento 15", "[Verificar pagamento 15]"),
    ("Método Pagamento 16", "<Cartão>", "Verificação Pagamento 16", "[Verificar pagamento 16]"),
    ("Método Pagamento 17", "<Cartão>", "Verificação Pagamento 17", "[Verificar pagamento 17]"),
    ("Método Pagamento 18", "<Cartão>", "Verificação Pagamento 18", "[Verificar pagamento 18]"),
    ("Método Pagamento 19", "<Cartão>", "Verificação Pagamento 19", "[Verificar pagamento 19]"),
    ("Método Pagamento 20", "<Cartão>", "Verificação Pagamento 20", "[Verificar pagamento 20]"),
    ("Método Pagamento 1", "<Dinheiro>", "Verificação Pagamento 1", "[Verificar pagamento 1]"),
    ("Método Pagamento 2", "<Dinheiro>", "Verificação Pagamento 2", "[Verificar pagamento 2]"),
    ("Método Pagamento 3", "<Dinheiro>", "Verificação Pagamento 3", "[Verificar pagamento 3]"),
    ("Método Pagamento 4", "<Dinheiro>", "Verificação Pagamento 4", "[Verificar pagamento 4]"),
    ("Método Pagamento 5", "<Dinheiro>", "Verificação Pagamento 5", "[Verificar pagamento 5]"),
    ("Método Pagamento 6", "<Dinheiro>", "Verificação Pagamento 6", "[Verificar pagamento 6]"),
    ("Método Pagamento 7", "<Dinheiro>", "Verificação Pagamento 7", "[Verificar pagamento 7]"),
    ("Método Pagamento 8", "<Dinheiro>", "Verificação Pagamento 8", "[Verificar pagamento 8]"),
    ("Método Pagamento 9", "<Dinheiro>", "Verificação Pagamento 9", "[Verificar pagamento 9]"),
    ("Método Pagamento 10", "<Dinheiro>", "Verificação Pagamento 10", "[Verificar pagamento 10]"),
    ("Método Pagamento 11", "<Dinheiro>", "Verificação Pagamento 11", "[Verificar pagamento 11]"),
    ("Método Pagamento 12", "<Dinheiro>", "Verificação Pagamento 12", "[Verificar pagamento 12]"),
    ("Método Pagamento 13", "<Dinheiro>", "Verificação Pagamento 13", "[Verificar pagamento 13]"),
    ("Método Pagamento 14", "<Dinheiro>", "Verificação Pagamento 14", "[Verificar pagamento 14]"),
    ("Método Pagamento 15", "<Dinheiro>", "Verificação Pagamento 15", "[Verificar pagamento 15]"),
    ("Método Pagamento 16", "<Dinheiro>", "Verificação Pagamento 16", "[Verificar pagamento 16]"),
    ("Método Pagamento 17", "<Dinheiro>", "Verificação Pagamento 17", "[Verificar pagamento 17]"),
    ("Método Pagamento 18", "<Dinheiro>", "Verificação Pagamento 18", "[Verificar pagamento 18]"),
    ("Método Pagamento 19", "<Dinheiro>", "Verificação Pagamento 19", "[Verificar pagamento 19]"),
    ("Método Pagamento 20", "<Dinheiro>", "Verificação Pagamento 20", "[Verificar pagamento 20]"),
    ("Verificação Pagamento 1", "(Falha 1)", "Venda", "Falha no pagamento"),
    ("Verificação Pagamento 2", "(Falha 2)", "Venda", "Falha no pagamento"),
    ("Verificação Pagamento 3", "(Falha 3)", "Venda", "Falha no pagamento"),
    ("Verificação Pagamento 4", "(Falha 4)", "Venda", "Falha no pagamento"),
    ("Verificação Pagamento 5", "(Falha 5)", "Venda", "Falha no pagamento"),
    ("Verificação Pagamento 6", "(Falha 6)", "Venda", "Falha no pagamento"),
    ("Verificação Pagamento 7", "(Falha 7)", "Venda", "Falha no pagamento"),
    ("Verificação Pagamento 8", "(Falha 8)", "Venda", "Falha no pagamento"),
    ("Verificação Pagamento 9", "(Falha 9)", "Venda", "Falha no pagamento"),
    ("Verificação Pagamento 10", "(Falha 10)", "Venda", "Falha no pagamento"),
    ("Verificação Pagamento 11", "(Falha 11)", "Venda", "Falha no pagamento"),
    ("Verificação Pagamento 12", "(Falha 12)", "Venda", "Falha no pagamento"),
    ("Verificação Pagamento 13", "(Falha 13)", "Venda", "Falha no pagamento"),
    ("Verificação Pagamento 14", "(Falha 14)", "Venda", "Falha no pagamento"),
    ("Verificação Pagamento 15", "(Falha 15)", "Venda", "Falha no pagamento"),
    ("Verificação Pagamento 16", "(Falha 16)", "Venda", "Falha no pagamento"),
    ("Verificação Pagamento 17", "(Falha 17)", "Venda", "Falha no pagamento"),
    ("Verificação Pagamento 18", "(Falha 18)", "Venda", "Falha no pagamento"),
    ("Verificação Pagamento 19", "(Falha 19)", "Venda", "Falha no pagamento"),
    ("Verificação Pagamento 20", "(Falha 20)", "Venda", "Falha no pagamento"),
    ("Verificação Pagamento 1", "(Aceito 1)", "Base", "Pagamento aceito, retire seu produto"),
    ("Verificação Pagamento 2", "(Aceito 2)", "Base", "Pagamento aceito, retire seu produto"),
    ("Verificação Pagamento 3", "(Aceito 3)", "Base", "Pagamento aceito, retire seu produto"),
    ("Verificação Pagamento 4", "(Aceito 4)", "Base", "Pagamento aceito, retire seu produto"),
    ("Verificação Pagamento 5", "(Aceito 5)", "Base", "Pagamento aceito, retire seu produto"),
    ("Verificação Pagamento 6", "(Aceito 6)", "Base", "Pagamento aceito, retire seu produto"),
    ("Verificação Pagamento 7", "(Aceito 7)", "Base", "Pagamento aceito, retire seu produto"),
    ("Verificação Pagamento 8", "(Aceito 8)", "Base", "Pagamento aceito, retire seu produto"),
    ("Verificação Pagamento 9", "(Aceito 9)", "Base", "Pagamento aceito, retire seu produto"),
    ("Verificação Pagamento 10", "(Aceito 10)", "Base", "Pagamento aceito, retire seu produto"),
    ("Verificação Pagamento 11", "(Aceito 11)", "Base", "Pagamento aceito, retire seu produto"),
    ("Verificação Pagamento 12", "(Aceito 12)", "Base", "Pagamento aceito, retire seu produto"),
    ("Verificação Pagamento 13", "(Aceito 13)", "Base", "Pagamento aceito, retire seu produto"),
    ("Verificação Pagamento 14", "(Aceito 14)", "Base", "Pagamento aceito, retire seu produto"),
    ("Verificação Pagamento 15", "(Aceito 15)", "Base", "Pagamento aceito, retire seu produto"),
    ("Verificação Pagamento 16", "(Aceito 16)", "Base", "Pagamento aceito, retire seu produto"),
    ("Verificação Pagamento 17", "(Aceito 17)", "Base", "Pagamento aceito, retire seu produto"),
    ("Verificação Pagamento 18", "(Aceito 18)", "Base", "Pagamento aceito, retire seu produto"),
    ("Verificação Pagamento 19", "(Aceito 19)", "Base", "Pagamento aceito, retire seu produto"),
    ("Verificação Pagamento 20", "(Aceito 20)", "Base", "Pagamento aceito, retire seu produto")
    ]
#estado inicial
q0 = Q[0]
#estados finais
F = [Q]
#saidas
delta = [
 "ε", "[Verificar Identificação]", "Id inválida, tente novamente", "Maquina desabilitada para manutenção", "Voltando a operação normal", "Digite o ID do produto", "Repor 1, Tudo ou Voltar?", "Reposto 1 Item", "Reposto todos Itens", 
 "Qual ID do produto?", "Voltando Menu Inicial", "Verificando estoque", "Estoque vazio, escolha outro item", "Qual metodo de pagamento?", "Falha no pagamento", "Pagamento aceito, retire seu produto", 
 "[Repor 1 1]", "[Repor 1 2]", "[Repor 1 3]", "[Repor 1 4]", "[Repor 1 5]", "[Repor 1 6]", "[Repor 1 7]", "[Repor 1 8]", "[Repor 1 9]", "[Repor 1 10]", 
 "[Repor 1 11]", "[Repor 1 12]", "[Repor 1 13]", "[Repor 1 14]", "[Repor 1 15]", "[Repor 1 16]", "[Repor 1 17]", "[Repor 1 18]", "[Repor 1 19]", "[Repor 1 20]", 
 "[Repor Tudo 1]", "[Repor Tudo 2]", "[Repor Tudo 3]", "[Repor Tudo 4]", "[Repor Tudo 5]", "[Repor Tudo 6]", "[Repor Tudo 7]", "[Repor Tudo 8]", "[Repor Tudo 9]", "[Repor Tudo 10]", 
 "[Repor Tudo 11]", "[Repor Tudo 12]", "[Repor Tudo 13]", "[Repor Tudo 14]", "[Repor Tudo 15]", "[Repor Tudo 16]", "[Repor Tudo 17]", "[Repor Tudo 18]", "[Repor Tudo 19]", "[Repor Tudo 20]", 
 "[Verificar estoque 1]", "[Verificar estoque 2]", "[Verificar estoque 3]", "[Verificar estoque 4]", "[Verificar estoque 5]", "[Verificar estoque 6]", "[Verificar estoque 7]", "[Verificar estoque 8]", "[Verificar estoque 9]", "[Verificar estoque 10]", 
 "[Verificar estoque 11]", "[Verificar estoque 12]", "[Verificar estoque 13]", "[Verificar estoque 14]", "[Verificar estoque 15]", "[Verificar estoque 16]", "[Verificar estoque 17]", "[Verificar estoque 18]", "[Verificar estoque 19]", "[Verificar estoque 20]", 
 "[Verificar pagamento 1]", "[Verificar pagamento 2]", "[Verificar pagamento 3]", "[Verificar pagamento 4]", "[Verificar pagamento 5]", "[Verificar pagamento 6]", "[Verificar pagamento 7]", "[Verificar pagamento 8]", "[Verificar pagamento 9]", "[Verificar pagamento 10]", 
 "[Verificar pagamento 11]", "[Verificar pagamento 12]", "[Verificar pagamento 13]", "[Verificar pagamento 14]", "[Verificar pagamento 15]", "[Verificar pagamento 16]", "[Verificar pagamento 17]", "[Verificar pagamento 18]", "[Verificar pagamento 19]", "[Verificar pagamento 20]"]
#estado atual
qx = q0
